"""Signatures for well-known web-proxy software landing pages.

Each entry scores independently; the landing detector returns the highest match.
Weights reflect how unique each signal is — "Glype" in a meta-generator is
essentially definitive, whereas a generic URL-input form is only suggestive.
"""

from __future__ import annotations

import re
from dataclasses import dataclass


@dataclass(frozen=True)
class Signature:
    name: str
    weight: float
    patterns: tuple[re.Pattern[str], ...]
    required_hits: int = 1


def _compile(*raws: str) -> tuple[re.Pattern[str], ...]:
    return tuple(re.compile(r, re.IGNORECASE) for r in raws)


SIGNATURES: tuple[Signature, ...] = (
    Signature(
        "glype",
        0.95,
        _compile(
            r'<meta[^>]+name=["\']generator["\'][^>]+glype',
            r"glype\s*v?\d",
            r"action=['\"][^'\"]*browse\.php",
            r"powered by\s+glype",
        ),
    ),
    Signature(
        "phproxy",
        0.9,
        _compile(
            r"phproxy",
            r"poxy",
            r"index\.php\?q=[a-z0-9]+",
            r"name=['\"]q['\"][^>]*>\s*<input[^>]*type=['\"]submit",
        ),
    ),
    Signature(
        "cgiproxy",
        0.95,
        _compile(
            r"cgiproxy",
            r"nph-proxy\.cgi",
            r"james marshall",
        ),
    ),
    Signature(
        "squid",
        0.7,
        _compile(
            r"squid/[0-9.]+",
            r"generated by squid",
            r"cache_object://",
        ),
    ),
    Signature(
        "privoxy",
        0.85,
        _compile(
            r"privoxy",
            r"config\.privoxy\.org",
        ),
    ),
    Signature(
        "3proxy",
        0.85,
        _compile(
            r"3proxy\s*[0-9.]+",
            r"3APA3A",
        ),
    ),
    Signature(
        "generic_url_form",
        0.45,
        _compile(
            r"enter\s+(a\s+)?(url|web\s*address)",
            r"browse\s+anonymously",
            r"unblock\s+(sites|websites|youtube|facebook)",
            r"free\s+web\s+proxy",
        ),
        required_hits=2,
    ),
)


def match(html: str) -> list[tuple[Signature, int]]:
    """Return all signatures that meet their `required_hits` threshold, with hit counts."""
    out: list[tuple[Signature, int]] = []
    for sig in SIGNATURES:
        hits = sum(1 for p in sig.patterns if p.search(html))
        if hits >= sig.required_hits:
            out.append((sig, hits))
    return out
